// @ts-nocheck
// Note: Type checking is disabled until `anchor build` generates proper IDL types
// The types will be fully checked once Solana SDK is installed and IDLs are generated

import * as anchor from "@coral-xyz/anchor";
import { Program, BN } from "@coral-xyz/anchor";
import { PublicKey, Keypair, SystemProgram, SYSVAR_RENT_PUBKEY } from "@solana/web3.js";
import {
  TOKEN_PROGRAM_ID,
  createMint,
  createAccount,
  mintTo,
  getAccount,
  getAssociatedTokenAddress,
  createAssociatedTokenAccountInstruction,
} from "@solana/spl-token";
import { expect } from "chai";
import * as crypto from "crypto";

// Note: IDL types are generated by `anchor build`
// Using 'any' for type checking until anchor build is run with Solana SDK

describe("DFPN Integration Tests", () => {
  // Configure the client
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  // Programs (typed as any until anchor build generates proper IDL types)
  let contentRegistry: Program<any>;
  let workerRegistry: Program<any>;
  let modelRegistry: Program<any>;
  let analysisMarketplace: Program<any>;
  let rewards: Program<any>;

  // Test accounts
  let dfpnMint: PublicKey;
  let treasuryAuthority: Keypair;
  let requester: Keypair;
  let worker1: Keypair;
  let worker2: Keypair;
  let worker3: Keypair;
  let modelDeveloper: Keypair;
  let challenger: Keypair;

  // Token accounts
  let requesterTokenAccount: PublicKey;
  let worker1TokenAccount: PublicKey;
  let worker2TokenAccount: PublicKey;
  let worker3TokenAccount: PublicKey;
  let modelDeveloperTokenAccount: PublicKey;
  let challengerTokenAccount: PublicKey;

  // PDAs
  let treasuryPda: PublicKey;
  let treasuryBump: number;
  let feeVaultPda: PublicKey;
  let feeVaultBump: number;
  let epochConfigPda: PublicKey;

  // State tracking
  let contentPda: PublicKey;
  let workerPda1: PublicKey;
  let workerPda2: PublicKey;
  let modelPda: PublicKey;
  let requestPda: PublicKey;

  // Constants
  const INITIAL_MINT_AMOUNT = new BN(1_000_000_000_000_000); // 1M DFPN
  const WORKER_STAKE = new BN(5_000_000_000_000); // 5,000 DFPN
  const MODEL_STAKE = new BN(20_000_000_000_000); // 20,000 DFPN
  const REQUEST_FEE = new BN(100_000_000_000); // 100 DFPN
  const DISPUTE_STAKE = new BN(1_000_000_000_000); // 1,000 DFPN

  // Seeds
  const SEEDS = {
    CONTENT: Buffer.from("content"),
    REQUEST: Buffer.from("request"),
    COMMIT: Buffer.from("commit"),
    REVEAL: Buffer.from("reveal"),
    WORKER: Buffer.from("worker"),
    MODEL: Buffer.from("model"),
    TREASURY: Buffer.from("treasury"),
    REWARD: Buffer.from("reward"),
    STAKE_VAULT: Buffer.from("stake_vault"),
    FEE_VAULT: Buffer.from("fee_vault"),
    DISPUTE: Buffer.from("dispute"),
    EPOCH: Buffer.from("epoch"),
  };

  before(async () => {
    // Load programs
    contentRegistry = anchor.workspace.ContentRegistry as Program<any>;
    workerRegistry = anchor.workspace.WorkerRegistry as Program<any>;
    modelRegistry = anchor.workspace.ModelRegistry as Program<any>;
    analysisMarketplace = anchor.workspace.AnalysisMarketplace as Program<any>;
    rewards = anchor.workspace.Rewards as Program<any>;

    console.log("Programs loaded:");
    console.log("  Content Registry:", contentRegistry.programId.toBase58());
    console.log("  Worker Registry:", workerRegistry.programId.toBase58());
    console.log("  Model Registry:", modelRegistry.programId.toBase58());
    console.log("  Analysis Marketplace:", analysisMarketplace.programId.toBase58());
    console.log("  Rewards:", rewards.programId.toBase58());

    // Generate keypairs
    treasuryAuthority = Keypair.generate();
    requester = Keypair.generate();
    worker1 = Keypair.generate();
    worker2 = Keypair.generate();
    worker3 = Keypair.generate();
    modelDeveloper = Keypair.generate();
    challenger = Keypair.generate();

    // Airdrop SOL to all accounts
    const airdropAmount = 100 * anchor.web3.LAMPORTS_PER_SOL;
    const accounts = [
      treasuryAuthority,
      requester,
      worker1,
      worker2,
      worker3,
      modelDeveloper,
      challenger,
    ];

    for (const account of accounts) {
      const sig = await provider.connection.requestAirdrop(
        account.publicKey,
        airdropAmount
      );
      await provider.connection.confirmTransaction(sig, "confirmed");
    }

    console.log("Airdrops complete");

    // Create DFPN mint
    dfpnMint = await createMint(
      provider.connection,
      treasuryAuthority,
      treasuryAuthority.publicKey,
      null,
      9 // 9 decimals
    );

    console.log("DFPN Mint created:", dfpnMint.toBase58());

    // Create token accounts and mint tokens
    const tokenAccounts = [
      { keypair: requester, name: "requester" },
      { keypair: worker1, name: "worker1" },
      { keypair: worker2, name: "worker2" },
      { keypair: worker3, name: "worker3" },
      { keypair: modelDeveloper, name: "modelDeveloper" },
      { keypair: challenger, name: "challenger" },
    ];

    for (const { keypair, name } of tokenAccounts) {
      const tokenAccount = await createAccount(
        provider.connection,
        keypair,
        dfpnMint,
        keypair.publicKey
      );

      await mintTo(
        provider.connection,
        treasuryAuthority,
        dfpnMint,
        tokenAccount,
        treasuryAuthority,
        BigInt(INITIAL_MINT_AMOUNT.toString())
      );

      // Store token account references
      switch (name) {
        case "requester":
          requesterTokenAccount = tokenAccount;
          break;
        case "worker1":
          worker1TokenAccount = tokenAccount;
          break;
        case "worker2":
          worker2TokenAccount = tokenAccount;
          break;
        case "worker3":
          worker3TokenAccount = tokenAccount;
          break;
        case "modelDeveloper":
          modelDeveloperTokenAccount = tokenAccount;
          break;
        case "challenger":
          challengerTokenAccount = tokenAccount;
          break;
      }
    }

    console.log("Token accounts created and funded");

    // Derive treasury PDA
    [treasuryPda, treasuryBump] = PublicKey.findProgramAddressSync(
      [SEEDS.TREASURY],
      rewards.programId
    );

    // Derive fee vault PDA
    [feeVaultPda, feeVaultBump] = PublicKey.findProgramAddressSync(
      [SEEDS.FEE_VAULT],
      rewards.programId
    );

    // Derive epoch config PDA
    [epochConfigPda] = PublicKey.findProgramAddressSync(
      [SEEDS.EPOCH, treasuryPda.toBuffer()],
      rewards.programId
    );

    console.log("\nSetup complete:");
    console.log("  Treasury PDA:", treasuryPda.toBase58());
    console.log("  Fee Vault PDA:", feeVaultPda.toBase58());
  });

  describe("1. Rewards Program - Treasury Setup", () => {
    it("should initialize treasury with correct shares", async () => {
      const workerShareBps = 6500; // 65%
      const modelShareBps = 2000; // 20%
      const treasuryShareBps = 1000; // 10%
      const insuranceShareBps = 500; // 5%

      await rewards.methods
        .initializeTreasury(
          workerShareBps,
          modelShareBps,
          treasuryShareBps,
          insuranceShareBps
        )
        .accounts({
          authority: treasuryAuthority.publicKey,
          treasury: treasuryPda,
          dfpnMint: dfpnMint,
          feeVault: feeVaultPda,
          tokenProgram: TOKEN_PROGRAM_ID,
          systemProgram: SystemProgram.programId,
          rent: SYSVAR_RENT_PUBKEY,
        })
        .signers([treasuryAuthority])
        .rpc();

      const treasuryAccount = await (rewards.account as any).treasuryConfig.fetch(treasuryPda);
      expect(treasuryAccount.workerShareBps).to.equal(workerShareBps);
      expect(treasuryAccount.modelShareBps).to.equal(modelShareBps);
      expect(treasuryAccount.treasuryShareBps).to.equal(treasuryShareBps);
      expect(treasuryAccount.insuranceShareBps).to.equal(insuranceShareBps);
      expect(treasuryAccount.paused).to.be.false;

      console.log("Treasury initialized successfully");
    });

    it("should initialize epoch tracking", async () => {
      const epochDurationSlots = new BN(216000); // ~24 hours

      await rewards.methods
        .initializeEpoch(epochDurationSlots)
        .accounts({
          authority: treasuryAuthority.publicKey,
          treasury: treasuryPda,
          epochConfig: epochConfigPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([treasuryAuthority])
        .rpc();

      const epochConfig = await (rewards.account as any).epochConfig.fetch(epochConfigPda);
      expect(epochConfig.currentEpoch.toNumber()).to.equal(0);
      expect(epochConfig.epochDurationSlots.eq(epochDurationSlots)).to.be.true;

      console.log("Epoch tracking initialized");
    });
  });

  describe("2. Worker Registry", () => {
    it("should register worker1 with stake", async () => {
      // Derive worker PDA
      [workerPda1] = PublicKey.findProgramAddressSync(
        [SEEDS.WORKER, worker1.publicKey.toBuffer()],
        workerRegistry.programId
      );

      // Derive stake vault PDA
      const [stakeVaultPda] = PublicKey.findProgramAddressSync(
        [SEEDS.STAKE_VAULT, worker1.publicKey.toBuffer()],
        workerRegistry.programId
      );

      const modalities = Modality.IMAGE_AUTHENTICITY | Modality.FACE_MANIPULATION;
      const endpoint = "https://worker1.dfpn.io";

      await workerRegistry.methods
        .registerWorker(modalities, endpoint)
        .accounts({
          operator: worker1.publicKey,
          workerAccount: workerPda1,
          stakeSource: worker1TokenAccount,
          stakeVault: stakeVaultPda,
          dfpnMint: dfpnMint,
          tokenProgram: TOKEN_PROGRAM_ID,
          systemProgram: SystemProgram.programId,
          rent: SYSVAR_RENT_PUBKEY,
        })
        .signers([worker1])
        .rpc();

      const workerAccount = await (workerRegistry.account as any).workerAccount.fetch(workerPda1);
      expect(workerAccount.operator.equals(worker1.publicKey)).to.be.true;
      expect(workerAccount.stake.gte(WORKER_STAKE)).to.be.true;

      console.log("Worker 1 registered:", workerPda1.toBase58());
    });

    it("should register worker2 with stake", async () => {
      [workerPda2] = PublicKey.findProgramAddressSync(
        [SEEDS.WORKER, worker2.publicKey.toBuffer()],
        workerRegistry.programId
      );

      const [stakeVaultPda] = PublicKey.findProgramAddressSync(
        [SEEDS.STAKE_VAULT, worker2.publicKey.toBuffer()],
        workerRegistry.programId
      );

      const modalities = Modality.IMAGE_AUTHENTICITY | Modality.VIDEO_AUTHENTICITY;
      const endpoint = "https://worker2.dfpn.io";

      await workerRegistry.methods
        .registerWorker(modalities, endpoint)
        .accounts({
          operator: worker2.publicKey,
          workerAccount: workerPda2,
          stakeSource: worker2TokenAccount,
          stakeVault: stakeVaultPda,
          dfpnMint: dfpnMint,
          tokenProgram: TOKEN_PROGRAM_ID,
          systemProgram: SystemProgram.programId,
          rent: SYSVAR_RENT_PUBKEY,
        })
        .signers([worker2])
        .rpc();

      console.log("Worker 2 registered:", workerPda2.toBase58());
    });

    it("should update worker modalities", async () => {
      const newModalities =
        Modality.IMAGE_AUTHENTICITY |
        Modality.FACE_MANIPULATION |
        Modality.GENERATED_CONTENT;

      await workerRegistry.methods
        .updateModalities(newModalities)
        .accounts({
          operator: worker1.publicKey,
          workerAccount: workerPda1,
        })
        .signers([worker1])
        .rpc();

      const workerAccount = await (workerRegistry.account as any).workerAccount.fetch(workerPda1);
      expect(workerAccount.supportedModalities.toString()).to.include("0");

      console.log("Worker 1 modalities updated");
    });
  });

  describe("3. Model Registry", () => {
    it("should register a detection model", async () => {
      const modelId = crypto.randomBytes(32);

      [modelPda] = PublicKey.findProgramAddressSync(
        [SEEDS.MODEL, modelId],
        modelRegistry.programId
      );

      const [stakeVaultPda] = PublicKey.findProgramAddressSync(
        [SEEDS.STAKE_VAULT, modelId],
        modelRegistry.programId
      );

      const name = "DeepfakeDetector-v1";
      const version = "1.0.0";
      const modalities = Modality.IMAGE_AUTHENTICITY | Modality.FACE_MANIPULATION;
      const modelUri = "ipfs://QmModelWeights...";
      const checksum = crypto.randomBytes(32);

      await modelRegistry.methods
        .registerModel(
          Array.from(modelId),
          name,
          version,
          modalities,
          modelUri,
          Array.from(checksum)
        )
        .accounts({
          developer: modelDeveloper.publicKey,
          modelAccount: modelPda,
          stakeSource: modelDeveloperTokenAccount,
          stakeVault: stakeVaultPda,
          dfpnMint: dfpnMint,
          tokenProgram: TOKEN_PROGRAM_ID,
          systemProgram: SystemProgram.programId,
          rent: SYSVAR_RENT_PUBKEY,
        })
        .signers([modelDeveloper])
        .rpc();

      const modelAccount = await (modelRegistry.account as any).modelAccount.fetch(modelPda);
      expect(modelAccount.name).to.equal(name);
      expect(modelAccount.version).to.equal(version);

      console.log("Model registered:", modelPda.toBase58());
    });

    it("should activate model after evaluation", async () => {
      await modelRegistry.methods
        .activateModel()
        .accounts({
          authority: treasuryAuthority.publicKey,
          modelAccount: modelPda,
        })
        .signers([treasuryAuthority])
        .rpc();

      const modelAccount = await (modelRegistry.account as any).modelAccount.fetch(modelPda);
      expect(modelAccount.status).to.deep.equal({ active: {} });

      console.log("Model activated");
    });
  });

  describe("4. Content Registry", () => {
    it("should register content", async () => {
      const contentData = Buffer.from("Test image content for deepfake detection");
      const contentHash = computeContentHash(contentData);

      [contentPda] = PublicKey.findProgramAddressSync(
        [SEEDS.CONTENT, contentHash],
        contentRegistry.programId
      );

      const mediaType = { image: {} };
      const storageUri = "ipfs://QmTestContent...";

      await contentRegistry.methods
        .registerContent(Array.from(contentHash), mediaType, storageUri)
        .accounts({
          creator: requester.publicKey,
          contentAccount: contentPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([requester])
        .rpc();

      const contentAccount = await (contentRegistry.account as any).contentEntry.fetch(contentPda);
      expect(Buffer.from(contentAccount.contentHash).equals(contentHash)).to.be.true;
      expect(contentAccount.storageUri).to.equal(storageUri);

      console.log("Content registered:", contentPda.toBase58());
    });
  });

  describe("5. Analysis Marketplace - Full Commit-Reveal Flow", () => {
    let requestNonce: BN;
    let contentHash: Buffer;
    let commitPda1: PublicKey;
    let commitPda2: PublicKey;
    let revealPda1: PublicKey;
    let revealPda2: PublicKey;
    let feeEscrowPda: PublicKey;

    // Worker secrets for commit-reveal
    let salt1: Buffer;
    let salt2: Buffer;
    let detectionsHash: Buffer;

    before(() => {
      contentHash = computeContentHash(Buffer.from("Test content for analysis"));
      requestNonce = new BN(Date.now());
      salt1 = crypto.randomBytes(16);
      salt2 = crypto.randomBytes(16);
      detectionsHash = crypto.randomBytes(32);
    });

    it("should create an analysis request", async () => {
      [requestPda] = PublicKey.findProgramAddressSync(
        [SEEDS.REQUEST, contentHash, requestNonce.toArrayLike(Buffer, "le", 8)],
        analysisMarketplace.programId
      );

      [feeEscrowPda] = PublicKey.findProgramAddressSync(
        [
          SEEDS.FEE_VAULT,
          SEEDS.REQUEST,
          contentHash,
          requestNonce.toArrayLike(Buffer, "le", 8),
        ],
        analysisMarketplace.programId
      );

      const storageUri = "ipfs://QmRequestContent...";
      const requiredModalities = Modality.IMAGE_AUTHENTICITY;
      const minWorkers = 2;
      const deadline = new BN(Math.floor(Date.now() / 1000) + 3600); // 1 hour

      await analysisMarketplace.methods
        .createRequest(
          Array.from(contentHash),
          storageUri,
          requiredModalities,
          minWorkers,
          REQUEST_FEE,
          deadline,
          requestNonce
        )
        .accounts({
          requester: requester.publicKey,
          requestAccount: requestPda,
          feeSource: requesterTokenAccount,
          feeEscrow: feeEscrowPda,
          dfpnMint: dfpnMint,
          tokenProgram: TOKEN_PROGRAM_ID,
          systemProgram: SystemProgram.programId,
          rent: SYSVAR_RENT_PUBKEY,
        })
        .signers([requester])
        .rpc();

      const requestAccount = await (analysisMarketplace.account as any).analysisRequest.fetch(
        requestPda
      );
      expect(requestAccount.requester.equals(requester.publicKey)).to.be.true;
      expect(requestAccount.feeAmount.eq(REQUEST_FEE)).to.be.true;
      expect(requestAccount.status).to.deep.equal({ open: {} });

      console.log("Analysis request created:", requestPda.toBase58());
    });

    it("should allow worker1 to commit result", async () => {
      [commitPda1] = PublicKey.findProgramAddressSync(
        [SEEDS.COMMIT, requestPda.toBuffer(), worker1.publicKey.toBuffer()],
        analysisMarketplace.programId
      );

      // Compute commitment
      const commitment = computeCommitment(
        Verdict.MANIPULATED,
        85,
        detectionsHash,
        salt1,
        worker1.publicKey,
        requestPda
      );

      await analysisMarketplace.methods
        .commitResult(Array.from(commitment))
        .accounts({
          operator: worker1.publicKey,
          requestAccount: requestPda,
          workerAccount: workerPda1,
          commitAccount: commitPda1,
          systemProgram: SystemProgram.programId,
        })
        .signers([worker1])
        .rpc();

      const commitAccount = await (analysisMarketplace.account as any).commitment.fetch(
        commitPda1
      );
      expect(Buffer.from(commitAccount.commitment).equals(commitment)).to.be.true;
      expect(commitAccount.revealed).to.be.false;

      console.log("Worker 1 committed");
    });

    it("should allow worker2 to commit result", async () => {
      [commitPda2] = PublicKey.findProgramAddressSync(
        [SEEDS.COMMIT, requestPda.toBuffer(), worker2.publicKey.toBuffer()],
        analysisMarketplace.programId
      );

      const commitment = computeCommitment(
        Verdict.MANIPULATED,
        90,
        detectionsHash,
        salt2,
        worker2.publicKey,
        requestPda
      );

      await analysisMarketplace.methods
        .commitResult(Array.from(commitment))
        .accounts({
          operator: worker2.publicKey,
          requestAccount: requestPda,
          workerAccount: workerPda2,
          commitAccount: commitPda2,
          systemProgram: SystemProgram.programId,
        })
        .signers([worker2])
        .rpc();

      const requestAccount = await (analysisMarketplace.account as any).analysisRequest.fetch(
        requestPda
      );
      expect(requestAccount.commitCount).to.equal(2);

      console.log("Worker 2 committed");
    });

    it("should allow worker1 to reveal result after commit window", async () => {
      // Wait for commit window to close (simulated by advancing time in localnet)
      await new Promise((resolve) => setTimeout(resolve, 2000));

      [revealPda1] = PublicKey.findProgramAddressSync(
        [SEEDS.REVEAL, requestPda.toBuffer(), worker1.publicKey.toBuffer()],
        analysisMarketplace.programId
      );

      const verdict = { manipulated: {} };
      const confidence = 85;

      await analysisMarketplace.methods
        .revealResult(verdict, confidence, Array.from(detectionsHash), Array.from(salt1))
        .accounts({
          operator: worker1.publicKey,
          requestAccount: requestPda,
          commitAccount: commitPda1,
          revealAccount: revealPda1,
          modelAccount: modelPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([worker1])
        .rpc();

      const revealAccount = await (analysisMarketplace.account as any).reveal.fetch(
        revealPda1
      );
      expect(revealAccount.confidence).to.equal(confidence);

      console.log("Worker 1 revealed");
    });

    it("should allow worker2 to reveal result", async () => {
      [revealPda2] = PublicKey.findProgramAddressSync(
        [SEEDS.REVEAL, requestPda.toBuffer(), worker2.publicKey.toBuffer()],
        analysisMarketplace.programId
      );

      const verdict = { manipulated: {} };
      const confidence = 90;

      await analysisMarketplace.methods
        .revealResult(verdict, confidence, Array.from(detectionsHash), Array.from(salt2))
        .accounts({
          operator: worker2.publicKey,
          requestAccount: requestPda,
          commitAccount: commitPda2,
          revealAccount: revealPda2,
          modelAccount: modelPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([worker2])
        .rpc();

      const requestAccount = await (analysisMarketplace.account as any).analysisRequest.fetch(
        requestPda
      );
      expect(requestAccount.revealCount).to.equal(2);

      console.log("Worker 2 revealed");
    });

    it("should finalize request with consensus", async () => {
      await analysisMarketplace.methods
        .finalizeRequest()
        .accounts({
          payer: requester.publicKey,
          requestAccount: requestPda,
          feeEscrow: feeEscrowPda,
          feeVault: feeVaultPda,
          rewardsTreasury: treasuryPda,
          rewardsEpochConfig: epochConfigPda,
          rewardsProgram: rewards.programId,
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .remainingAccounts([
          { pubkey: revealPda1, isSigner: false, isWritable: false },
          { pubkey: revealPda2, isSigner: false, isWritable: false },
        ])
        .signers([requester])
        .rpc();

      const requestAccount = await (analysisMarketplace.account as any).analysisRequest.fetch(
        requestPda
      );
      expect(requestAccount.status).to.deep.equal({ finalized: {} });
      expect(requestAccount.finalVerdict).to.deep.equal({ manipulated: {} });
      expect(requestAccount.consensusType).to.deep.equal({ unanimous: {} });

      console.log("Request finalized with unanimous consensus");
    });
  });

  describe("6. Request Cancellation", () => {
    it("should allow requester to cancel request before commits", async () => {
      const contentHash = computeContentHash(Buffer.from("Cancel test content"));
      const requestNonce = new BN(Date.now());

      const [cancelRequestPda] = PublicKey.findProgramAddressSync(
        [SEEDS.REQUEST, contentHash, requestNonce.toArrayLike(Buffer, "le", 8)],
        analysisMarketplace.programId
      );

      const [feeEscrowPda] = PublicKey.findProgramAddressSync(
        [
          SEEDS.FEE_VAULT,
          SEEDS.REQUEST,
          contentHash,
          requestNonce.toArrayLike(Buffer, "le", 8),
        ],
        analysisMarketplace.programId
      );

      // Create request
      await analysisMarketplace.methods
        .createRequest(
          Array.from(contentHash),
          "ipfs://test",
          Modality.IMAGE_AUTHENTICITY,
          1,
          REQUEST_FEE,
          new BN(Math.floor(Date.now() / 1000) + 3600),
          requestNonce
        )
        .accounts({
          requester: requester.publicKey,
          requestAccount: cancelRequestPda,
          feeSource: requesterTokenAccount,
          feeEscrow: feeEscrowPda,
          dfpnMint: dfpnMint,
          tokenProgram: TOKEN_PROGRAM_ID,
          systemProgram: SystemProgram.programId,
          rent: SYSVAR_RENT_PUBKEY,
        })
        .signers([requester])
        .rpc();

      // Get balance before cancel
      const balanceBefore = await getAccount(provider.connection, requesterTokenAccount);

      // Cancel request
      await analysisMarketplace.methods
        .cancelRequest()
        .accounts({
          requester: requester.publicKey,
          requestAccount: cancelRequestPda,
          feeEscrow: feeEscrowPda,
          feeDestination: requesterTokenAccount,
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .signers([requester])
        .rpc();

      const requestAccount = await (analysisMarketplace.account as any).analysisRequest.fetch(
        cancelRequestPda
      );
      expect(requestAccount.status).to.deep.equal({ cancelled: {} });

      // Verify fee was refunded
      const balanceAfter = await getAccount(provider.connection, requesterTokenAccount);
      expect(
        BigInt(balanceAfter.amount.toString()) >
          BigInt(balanceBefore.amount.toString())
      ).to.be.true;

      console.log("Request cancelled and fee refunded");
    });
  });

  describe("7. Reward Claims", () => {
    it("should initialize reward account for worker", async () => {
      const [rewardAccountPda] = PublicKey.findProgramAddressSync(
        [SEEDS.REWARD, worker1.publicKey.toBuffer()],
        rewards.programId
      );

      await rewards.methods
        .initializeRewardAccount()
        .accounts({
          payer: worker1.publicKey,
          claimant: worker1.publicKey,
          rewardAccount: rewardAccountPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([worker1])
        .rpc();

      const rewardAccount = await (rewards.account as any).rewardAccount.fetch(rewardAccountPda);
      expect(rewardAccount.claimant.equals(worker1.publicKey)).to.be.true;
      expect(rewardAccount.pendingAmount.toNumber()).to.equal(0);

      console.log("Worker 1 reward account initialized");
    });
  });

  describe("8. Dispute Resolution", () => {
    let disputeRequestPda: PublicKey;
    let disputeRevealPda: PublicKey;
    let disputePda: PublicKey;
    let disputeEscrowPda: PublicKey;

    it("should allow challenger to open dispute on a result", async () => {
      // First create and finalize a request
      const contentHash = computeContentHash(Buffer.from("Dispute test content"));
      const requestNonce = new BN(Date.now());

      [disputeRequestPda] = PublicKey.findProgramAddressSync(
        [SEEDS.REQUEST, contentHash, requestNonce.toArrayLike(Buffer, "le", 8)],
        analysisMarketplace.programId
      );

      const [feeEscrowPda] = PublicKey.findProgramAddressSync(
        [
          SEEDS.FEE_VAULT,
          SEEDS.REQUEST,
          contentHash,
          requestNonce.toArrayLike(Buffer, "le", 8),
        ],
        analysisMarketplace.programId
      );

      // Create request
      await analysisMarketplace.methods
        .createRequest(
          Array.from(contentHash),
          "ipfs://dispute-test",
          Modality.IMAGE_AUTHENTICITY,
          1,
          REQUEST_FEE,
          new BN(Math.floor(Date.now() / 1000) + 3600),
          requestNonce
        )
        .accounts({
          requester: requester.publicKey,
          requestAccount: disputeRequestPda,
          feeSource: requesterTokenAccount,
          feeEscrow: feeEscrowPda,
          dfpnMint: dfpnMint,
          tokenProgram: TOKEN_PROGRAM_ID,
          systemProgram: SystemProgram.programId,
          rent: SYSVAR_RENT_PUBKEY,
        })
        .signers([requester])
        .rpc();

      // Worker commits and reveals
      const [commitPda] = PublicKey.findProgramAddressSync(
        [SEEDS.COMMIT, disputeRequestPda.toBuffer(), worker1.publicKey.toBuffer()],
        analysisMarketplace.programId
      );

      const salt = crypto.randomBytes(16);
      const detectionsHash = crypto.randomBytes(32);
      const commitment = computeCommitment(
        Verdict.AUTHENTIC,
        95,
        detectionsHash,
        salt,
        worker1.publicKey,
        disputeRequestPda
      );

      await analysisMarketplace.methods
        .commitResult(Array.from(commitment))
        .accounts({
          operator: worker1.publicKey,
          requestAccount: disputeRequestPda,
          workerAccount: workerPda1,
          commitAccount: commitPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([worker1])
        .rpc();

      await new Promise((resolve) => setTimeout(resolve, 1000));

      [disputeRevealPda] = PublicKey.findProgramAddressSync(
        [SEEDS.REVEAL, disputeRequestPda.toBuffer(), worker1.publicKey.toBuffer()],
        analysisMarketplace.programId
      );

      await analysisMarketplace.methods
        .revealResult(
          { authentic: {} },
          95,
          Array.from(detectionsHash),
          Array.from(salt)
        )
        .accounts({
          operator: worker1.publicKey,
          requestAccount: disputeRequestPda,
          commitAccount: commitPda,
          revealAccount: disputeRevealPda,
          modelAccount: modelPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([worker1])
        .rpc();

      // Finalize
      await analysisMarketplace.methods
        .finalizeRequest()
        .accounts({
          payer: requester.publicKey,
          requestAccount: disputeRequestPda,
          feeEscrow: feeEscrowPda,
          feeVault: feeVaultPda,
          rewardsTreasury: treasuryPda,
          rewardsEpochConfig: epochConfigPda,
          rewardsProgram: rewards.programId,
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .remainingAccounts([
          { pubkey: disputeRevealPda, isSigner: false, isWritable: false },
        ])
        .signers([requester])
        .rpc();

      // Now challenger opens dispute
      [disputePda] = PublicKey.findProgramAddressSync(
        [SEEDS.DISPUTE, disputeRequestPda.toBuffer(), disputeRevealPda.toBuffer()],
        analysisMarketplace.programId
      );

      [disputeEscrowPda] = PublicKey.findProgramAddressSync(
        [
          SEEDS.FEE_VAULT,
          SEEDS.DISPUTE,
          disputeRequestPda.toBuffer(),
          disputeRevealPda.toBuffer(),
        ],
        analysisMarketplace.programId
      );

      const evidenceHash = crypto.randomBytes(32);
      const disputeReason = { invalidResult: {} };

      await analysisMarketplace.methods
        .openDispute(disputeReason, Array.from(evidenceHash))
        .accounts({
          challenger: challenger.publicKey,
          requestAccount: disputeRequestPda,
          revealAccount: disputeRevealPda,
          disputeAccount: disputePda,
          challengerTokenAccount: challengerTokenAccount,
          disputeEscrow: disputeEscrowPda,
          dfpnMint: dfpnMint,
          tokenProgram: TOKEN_PROGRAM_ID,
          systemProgram: SystemProgram.programId,
          rent: SYSVAR_RENT_PUBKEY,
        })
        .signers([challenger])
        .rpc();

      const disputeAccount = await (analysisMarketplace.account as any).dispute.fetch(disputePda);
      expect(disputeAccount.challenger.equals(challenger.publicKey)).to.be.true;
      expect(disputeAccount.status).to.deep.equal({ open: {} });

      console.log("Dispute opened:", disputePda.toBase58());
    });

    it("should allow resolver to resolve dispute in favor of challenger", async () => {
      const slashAmount = new BN(500_000_000_000); // 500 DFPN

      await analysisMarketplace.methods
        .resolveDispute(true, slashAmount)
        .accounts({
          resolver: treasuryAuthority.publicKey,
          requestAccount: disputeRequestPda,
          disputeAccount: disputePda,
          disputeEscrow: disputeEscrowPda,
          challengerTokenAccount: challengerTokenAccount,
          treasuryVault: feeVaultPda,
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .signers([treasuryAuthority])
        .rpc();

      const disputeAccount = await (analysisMarketplace.account as any).dispute.fetch(disputePda);
      expect(disputeAccount.status).to.deep.equal({ resolvedForChallenger: {} });

      console.log("Dispute resolved in favor of challenger");
    });
  });
});

// ============================================================================
// Helper Functions
// ============================================================================

function computeContentHash(data: Buffer): Buffer {
  return crypto.createHash("sha256").update(data).digest();
}

function computeCommitment(
  verdict: number,
  confidence: number,
  detectionsHash: Buffer,
  salt: Buffer,
  worker: PublicKey,
  request: PublicKey
): Buffer {
  const hasher = crypto.createHash("sha256");
  hasher.update(Buffer.from([verdict, confidence]));
  hasher.update(detectionsHash);
  hasher.update(salt);
  hasher.update(worker.toBuffer());
  hasher.update(request.toBuffer());
  return hasher.digest();
}

// ============================================================================
// Constants
// ============================================================================

const Modality = {
  IMAGE_AUTHENTICITY: 1 << 0,
  VIDEO_AUTHENTICITY: 1 << 1,
  AUDIO_AUTHENTICITY: 1 << 2,
  FACE_MANIPULATION: 1 << 3,
  VOICE_CLONING: 1 << 4,
  GENERATED_CONTENT: 1 << 5,
};

const Verdict = {
  AUTHENTIC: 0,
  MANIPULATED: 1,
  INCONCLUSIVE: 2,
};
